### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zelongc**
listing Props in the README could help newbies (like me) save a lot of time from googling around how to config a ck-editor5 react component.

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Type: Message. Closes #000.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by pomek** [comment]
Hi @zelongc,

Thanks for the PR. However, all properties are listed in the documentation (https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#component-properties). The link to this page is located at the beginning of the README. 

I don't guess that repeating the same content will help.

**Comment by zelongc** [comment]
My concern was, there could be a lot of non-english speakers who can be eassily frightened by a screen of english characters just like me.. Providing a list of props in README doesn't hurt anyone and could potentially save them a lot of time.

Thanks for the review @pomek and your awesome work.

**Comment by Reinmar** [comment]
The question is whether this component can really be used without reading the docs. There are a couple of things one needs to know now to use it.

Also, we should be cautious to not make a false impression that this is the entire documentation here in the `README.md`. The more we'll add here, the bigger the chance that people will miss all the links to the actual documentation.

**Comment by Reinmar** [comment]
PS. That said – I believe we should improve the "Documentation" section because it's not very visible now either. @ma2ciek had the idea to put there the table of contents from https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html. What do you think about it?

**Pull request closed without merging**
