### PR TITLE
Include an example how to get the HTML out

### LINKED ISSUE #23: Add to Readme - "How to get the editor value?"
https://github.com/ckeditor/ckeditor5-react/issues/20#issuecomment-409592912

### PR DESCRIPTION
**Pull request by dawehner**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Include an example how to get HTML out. Closes #23

---

### Additional information

Let's make the life a bit easier for people to get HTML out

### CODE REVIEW

**Comment by pomek** [comment]
Hi @dawehner.

Thanks for the PR. Your changes make sense but I am not able to merge this because of awaiting [Contributor License Agreement signature](https://cla.ckeditor.com/check/ckeditor/ckeditor5-react/24). Could you sign it? Then we will be able to merge the PR.

**Comment by dawehner** [comment]
Thank you for the super quick response! I've downloaded the PDF and filled it out, but I can't see where to send it to. Do you mind giving me a pointer?

**Comment by vokiel** [comment]
@dawehner I see that you have your email masked on GH, thus the automatic system couldn't send you the sign request. Please [contact us](https://ckeditor.com/contact/) and drop us your e-mail address so we'll send you a link to the CLA (it's signed online with eSignLive provider).

**Comment by dawehner** [comment]
Send a super quick message over :)

**Comment by pomek** [comment]
Merged. Thanks, @dawehner.

**Pull request merged**
