### PR TITLE
Fixed resolving the peer dependencies

### PR DESCRIPTION
**Pull request by DawidKossowski**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Fixed resolving the peer dependencies.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by pomek** [comment]
@DawidKossowski, could you give a short explanation of why this change is needed?

**Review by filipsobol — APPROVED** [review]

**Comment by DawidKossowski** [comment]
Sure. Now, every package used in the source code is included in the build, even if it's listed in `peerDependencies`. For instance, we use Watchdog version `40.1.0` in React integration, which is also listed in the peer dependencies. However, it gets bundled into the file: https://cdn.jsdelivr.net/npm/@ckeditor/ckeditor5-react/dist/index.js, since it is not marked as external in the Webpack config. This leads to the issue that if the integrator installs Watchdog version `41.3.1`, it won't matter and won't be used since `ckeditor5-react` already includes this package.

Additionally, those packages will be duplicated in `node_modules` with different versions.

**Comment by pomek** [comment]
Thanks. I think the issue touches the Angular integration as well.

**Review by pomek — APPROVED** [review]

**Comment by Reinmar** [comment]
> Internal: Fixed resolving the peer dependencies.

Is it really an internal change? Why did we need a change? It's a pity we don't have an actually issue explaining why we're changing this.

[@DawidKossowski's comment](https://github.com/ckeditor/ckeditor5-react/pull/470#issuecomment-2063461771) mention issues with the published bundle, AFAIU. In this case, this PR is a bug fix. And should be mentioned in the changelog.

**Comment by pomek** [comment]
@Reinmar, I will handle it when the package is ready to release.

**Pull request merged**
